### ISSUE TITLE
django-storages compatibility

### ISSUE THREAD

**Issue by frobert** [codingjoe/django-pictures#112]
Hi, does anyone know if this plugin works with django-storages? I'm not able to make it work. With django-storages images are uploaded to S3 and with django-pictures I would like to generate WEBP images from originals on S3 ... Is this possible and does anyone have an example? Thank you. Best regards.

**Comment by vchrisb** [comment]
What problem are you facing? For me it is working straight forward.

**Comment by frobert** [comment]
Got it working, missed out Celery pictures queue.
