### ISSUE TITLE
Support for Django-RQ

### ISSUE THREAD

**Issue by krtko1** [codingjoe/django-pictures#122]
Consider support for [Django-RQ](https://github.com/rq/django-rq).

**Comment by codingjoe** [comment]
Hi @krtko1,

That's an excellent idea. Adding a new processor is fairly straightforward. All you have to do is wrap the synchronous processor in an asynchronous task. I am not too familiar with Django-RQ, and I'd appreciate your help if you'd like. Are you interested in contributing?

Cheers!
Joe

**Comment by krtko1** [comment]
I tried to implemented it, not sure how test in your project work

**Comment by codingjoe** [comment]
Wonderful, I left you a couple of comments on the PR itself. Thanks!
