### ISSUE TITLE
Django 5.0.x warnings with examples from documentation

### ISSUE THREAD

**Issue by frlan** [codingjoe/django-pictures#179]
When I just adopted the examples given in the README like
```
    logo = PictureField(
        upload_to='logo',
        blank=True,
        null=True)
```
I got thiese warnings:

```
`WARNINGS:
techtree.Item.logo: (fields.E101) width_field and height_field attributes are missing
	HINT: Please add two positive integer fields to 'techtree.Item' and add their field names as the 'width_field' and 'height_field' attribute for your picture field. Otherwise Django will not be able to cache the image aspect size causing disk IO and potential response time increases.
```

Inside example app I see there is some more code – but would be nice if the simplest examples in the README doesn't produce a warning ;)

**Comment by codingjoe** [comment]
Hi @frlan 👋

Thanks for reaching out. That is an excellent point, the "tutorial" (of sorts) should be exemplary. Would you care to extend the documentation yourself?

Cheers!
Joe

**Comment by codingjoe** [comment]
Closed due to inactivity.
