### ISSUE TITLE
Can not install django-pictures

### ISSUE THREAD

**Issue by pinpointconseil** [codingjoe/django-pictures#18]
Hi,
Can not install using this command: python3 -m pip install django-pictures

Here is the error in my terminal:

ERROR: Ignored the following versions that require a different python version: 1.0a1 Requires-Python >=3.10; 1.0a2 Requires-Python >=3.10; 1.0a3 Requires-Python >=3.10; 1.0a4 Requires-Python >=3.10; 1.0a5 Requires-Python >=3.10
ERROR: Could not find a version that satisfies the requirement django-pictures (from versions: none)
ERROR: No matching distribution found for django-picture

Do you have a way to install it? I'm using Python 3.7

**Comment by codingjoe** [comment]
@pinpointconseil can you do a quick `python --version` for me?

**Comment by codingjoe** [comment]
Oh sorry, I missed you last the sentence. I am afraid we only support Python 3.10 right now and are not likely to support any older version.

Of course, you can always contribute version support to this package, but 3.7 is a rather old Python version.
