### ISSUE TITLE
Document on how to use e.g. uuid based image names

### ISSUE THREAD

**Issue by frlan** [codingjoe/django-pictures#180]
Not all uploaded images are having quiet good name -- some even dangerous ones. It would be nice to clean such names prior and e.g. use UUID based names for images. It would be really cool if an approach for doing it could be found in documentation.

**Comment by codingjoe** [comment]
Hi @frlan,

I agree, it does make sense to change alter file names on upload.
If only, someone create a package for that… https://github.com/codingjoe/django-dynamic-filenames

😉 

I hope that helps. I do agree with your use case, but uploading files it superseding the purpose of this package. My other package should help you out.

Cheers!
Joe
