### ISSUE TITLE
Warning Fields.E101 Hint

### ISSUE THREAD

**Issue by alexwayne** [codingjoe/django-pictures#185]
Hi,

While running makemigrations using Django version 5.1.1 and  django-pictures 1.3.3, I got a warning:

> WARNINGS:
> items.Item.picture: (fields.E101) width_field and height_field attributes are missing
>         HINT: Please add two positive integer fields to 'items.Item' and add their field names as the 'width_field' and 'height_field' attribute for your picture field. Otherwise Django will not be able to cache the image aspect size causing disk IO and potential response time increases.

**Comment by codingjoe** [comment]
Hi @alexwayne,

Thank you for reaching out. The warning is part of this library to better inform people about potential performance drawbacks. If you have any specific questions, please don't hesitate to as the in the Q&A section in our discussion board here on GitHub.

Best
Joe

**Comment by alexwayne** [comment]
Sounds great! Thanks
