### ISSUE TITLE
django-pictures  using file  JPG   type format  throws an error  'JPG'

### ISSUE THREAD

**Issue by saeedblanchette** [codingjoe/django-pictures#32]
I'm trying to save  an instance in Django admin UI but it throws an error 
> KeyError at /admin/general/sitesetting/1/change/
> 
> 'JPG'

The error had faded away after I changed the FILE_TYPES  variable settings  from 
` "FILE_TYPES": ["WEBP","JPG"]`
to 
 "FILE_TYPES": ["WEBP"],

Is the format JPG not supported or it's a  Bug !?

**Comment by codingjoe** [comment]
Hi @saeedblanchette,

Excellent question. It's just a little spelling thing, you'll need to use the long abbreviation `JPEG` with an `E` and it should work.

Cheers,
Joe

PS: You unless you are serving Internet Explorer, there really isn't a need to use JPEGs anymore. See https://caniuse.com/webp

**Comment by saeedblanchette** [comment]
@codingjoe  Thank you for your answer
