### ISSUE TITLE
Should `aspect_ratios` default to `None`?

### ISSUE THREAD

**Issue by amureki** [codingjoe/django-pictures#33]
Greetings @codingjoe 

Trying out your package, looks great so far!
I noticed one thing, that I am not sure about. `aspect_ratios` is a non-required attribute, so I left it out:

```python
# models.py
class Picture(models.Model):
    image = PictureField(
        _("image"), upload_to=attached_to_id_pattern, blank=True, null=True
    )

# serializers.py

class PictureSerializer(serializers.ModelSerializer):
    image = PictureField()

    class Meta:
        model = models.Picture
        fields = ("id", "image")
```

After I did set the serializer with my fresh field and uploaded a picture, I ended up with the next payload:

```json
"pictures": [
        {
            "id": 1,
            "image": {
                "null": {
                    "WEBP": {
                        "100": "/media/picture/74/XSWP/100w.webp",
                        "200": "/media/picture/74/XSWP/200w.webp",
                        "300": "/media/picture/74/XSWP/300w.webp",
                        "400": "/media/picture/74/XSWP/400w.webp",
                        "500": "/media/picture/74/XSWP/500w.webp",
                        "600": "/media/picture/74/XSWP/600w.webp"
                    }
                }
            }
        }
    ]
```

As you can see, there is `null` value that does not look right in the payload. And it comes from the empty `aspect_ratios`.
Should it default to something more meaningful, like `"1/1"`? Also, I am missing out a bit on the documentation where and how `aspect_ratios` would be used and affect the result.

Cheers,
Rust

**Comment by codingjoe** [comment]
Hi @amureki,

Excellent discovery. Yes, that bit seems poorly documented. By default, we assume a null value. The null value is special, in that it doesn't enforce an aspect ratio, but will use the ratio of the original image.

I'd propose both changes to the documentation about null or `None` values and make the attribute required.

Are you, interested in contributing those changes?

Cheers,
Joe
