### ISSUE TITLE
Styling / Class on picture tag

### ISSUE THREAD

**Issue by SebastianKapunkt** [codingjoe/django-pictures#60]
In order to fully support customizability in styling for the images, it should be possible to add `style` or `class` to each of those. The two tags that I see are: `img` and `picture`. For `picture` it's currently not possible.

**Comment by codingjoe** [comment]
@SebastianKapunkt are you interested in implementing this? The magic, on how we pass attributes, happens mostly here
https://github.com/codingjoe/django-pictures/blob/acb0a0df59d746a587dc94a0c5b1606a93259f54/pictures/templatetags/pictures.py#L26-L27
and in the include here
https://github.com/codingjoe/django-pictures/blob/acb0a0df59d746a587dc94a0c5b1606a93259f54/pictures/templates/pictures/picture.html#L5
