### ISSUE TITLE
Exception while saving

### ISSUE THREAD

**Issue by 1r00t** [codingjoe/django-pictures#65]
Hey, I use this module in a project with django-rest-framwork, gunicorn and nginx.
When I try to upload a new file from my client/frontend in production I get this:

```
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7fa1d196a680>
Traceback (most recent call last):
  File "/usr/lib/python3.10/tempfile.py", line 589, in __del__
    self.close()
  File "/usr/lib/python3.10/tempfile.py", line 585, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmph9zpjln8.upload.jpg'
```

Locally with `runserver` I didn't have any problems.

Any ideas what I can do about that? I don't quite understand what is going on.
I found this: [random issue](https://github.com/OpenDroneMap/WebODM/issues/200#issuecomment-314160248)
But it doen't really help me.

**Comment by 1r00t** [comment]
Okay I fixed it for now with increasing timeouts.
Nginx:
```
 proxy_send_timeout 600;
 proxy_read_timeout 600;
```

Gunicorn:
````
gunicorn -t 600
````

I think I should use celery :S

**Comment by codingjoe** [comment]
Yes, that is highly recommended. That's why we default to asynchronous processing, when available. You really don't want to do image compression on the same system that serves requests. Since image compression requires more CPU and RAM and has almost no slow IO.
