### ISSUE TITLE
DRF Serializer Support

### ISSUE THREAD

**Issue by chgad** [codingjoe/django-pictures#7]
This is a long-shot suggestion.

How do you feel about including serializer support like it "was" provided [here](https://github.com/glemmaPaul/django-stdimage-serializer/blob/master/stdimage_serializer/fields.py#L4).

I'd be happy to contribute this in the near future.

**Comment by codingjoe** [comment]
@chgad excellent idea. Why not, it's such a common framework, let's make it happen.
